# https://files.minecraftforge.net/net/minecraftforge/forge/
modLoader = "javafml"
loaderVersion = "[41,)"
license = "GPL-3"
issueTrackerURL="https://github.com/p0t4t0sandwich/NamedEntityDeathMessages/issues"

[[mods]]
modId = "namedentitydeathmessages"
version = "${file.jarVersion}"
displayName = "NamedEntityDeathMessages"
updateJSONURL="https://raw.githubusercontent.com/p0t4t0sandwich/NamedEntityDeathMessages/main/forgeUpdates.json"
displayURL="https://github.com/p0t4t0sandwich/NamedEntityDeathMessages"
logoFile="NamedEntityDeathMessages.png"
credits="p0t4t0sandwich"
authors="p0t4t0sandwich"
displayTest="IGNORE_SERVER_VERSION"
description = '''
NamedEntityDeathMessages
'''

# Forge Dependency
[[dependencies.namedentitydeathmessages]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

# Minecraft Dependency
[[dependencies.namedentitydeathmessages]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
